# Generated by Django 4.2.6 on 2023-11-13 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Swarms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swarm_ID', models.IntegerField(default=0)),
                ('swarm_name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drones.users')),
            ],
        ),
        migrations.CreateModel(
            name='Drones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone_ID', models.IntegerField()),
                ('drone_name', models.CharField(max_length=250)),
                ('MAC_address', models.CharField(max_length=250)),
                ('IP_address', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('swarm_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drones.swarms')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drones.users')),
            ],
        ),
        migrations.CreateModel(
            name='AP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APID', models.IntegerField()),
                ('SSID', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('auth_method', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drones.users')),
            ],
        ),
    ]
