# Generated by Django 4.2.6 on 2023-11-20 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drones',
            new_name='Drone',
        ),
        migrations.RenameModel(
            old_name='Swarms',
            new_name='Swarm',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
