# Generated by Django 4.2.7 on 2023-12-01 03:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_rename_drones_drone_rename_swarms_swarm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ap',
            name='id',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='id',
        ),
        migrations.RemoveField(
            model_name='swarm',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='ap',
            name='APID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ap',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ap',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='drone',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='drone',
            name='drone_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drone',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='swarm',
            name='swarm_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
